version: '3'
services:
  new-summarizer-bot:
    image: mrxcrypt/news-summarizer-bot:latest
    container_name: news-summarizer-bot
    env_file:
      - .env
    command: ["python", "hfbot.py"]
    restart: unless-stopped